#!/bin/bash
# check for root permissions
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
# Stop all containers
docker stop $(docker ps -a -q)
# Delete all containers
docker rm $(docker ps -a -q)
# Delete all images
docker rmi $(docker images -q)
