#!/bin/bash

echo "Work in progress: not working yet"
exit;


USAGE=$"\n    Usage: filesize [file]\n"

if [ $# != 1 ];then
   echo -e $USAGE
   exit 1
fi

if [[ -f $1 ]]; then
    $(watch -n 1 "ls -l "$1" | awk '{print \$5}' | sed -re ' :rep ; s/([0-9])([0-9]{3})($|[^0-9])/\1,\2\3/ ; t rep '")
else
    echo "cannot read file "$1
fi
