#!/usr/bin/env bash
# ifconfig | grep "inet "
# ifconfig | grep "inet " | grep -o 'inet \d\{1,3\}\.\d\{1,3\}\.\d\{1,3\}\.\d\{1,3\}'
# ifconfig | grep "inet " | grep -o '\d\{1,3\}\.\d\{1,3\}\.\d\{1,3\}\.\d\{1,3\}'
# ifconfig | grep "inet " | grep -o "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
ifconfig | grep "inet " | grep -v 127.0.0.1
