#!/bin/bash
rsync -arv /media/$USER/Data/Data/android/   /media/$USER/FICOPEN/Data/android/                 --delete
rsync -arv /media/$USER/Data/Data/ESC201801/ /media/$USER/FICOPEN/Data/ESC201801/               --delete
rsync -arv /media/$USER/Data/Data/FICOSA/    /media/$USER/FICOPEN/Data/FICOSA/                  --delete
rsync -arv /media/$USER/Data/Data/img/       /media/$USER/FICOPEN/Data/img/                     --delete
rsync -arv /media/$USER/Data/Data/JSON/      /media/$USER/FICOPEN/Data/JSON/                    --delete
rsync -arv /media/$USER/Data/Data/OVH/       /media/$USER/FICOPEN/Data/OVH/                     --delete
rsync -arv /media/$USER/Data/Data/PERSONAL/  /media/$USER/FICOPEN/Data/PERSONAL/                --delete
rsync -arv --exclude="/Providers" /media/$USER/Data/Data/V2X/ /media/$USER/FICOPEN/Data/V2X/    --delete

PROJECTS_FOLDER=/home/$USER/Projects
PROJECTS_BACKUP=/media/$USER/FICOPEN/Projects
rsync -arv --exclude=".git" --exclude="proxImages" $PROJECTS_FOLDER/OVH/  $PROJECTS_BACKUP/OVH/                     --delete
rsync -arv --exclude=".git" $PROJECTS_FOLDER/php-system_releases_bd/      $PROJECTS_BACKUP/php-system_releases_bd/  --delete
rsync -arv --exclude=".git" --exclude-from="/home/lindsay/Projects/android-SafetyDemo/.gitignore" $PROJECTS_FOLDER/android-SafetyDemo/ $PROJECTS_BACKUP/android-SafetyDemo/ --delete

# rsync -arv --exclude="/Lindsay" --exclude="/trash" --exclude="/Ω" --exclude="/V2X/Providers" /media/$USER/Data/Data/ /media/$USER/FICOPEN/Data/
# DATA_FOLDER=/media/$USER/Data/Data
# DATA_BACKUP=/media/$USER/Data/Data
# PROJECTS_FOLDER=/home/$USER/Projects
# PROJECTS_BACKUP=/media/$USER/FICOPEN/Projects
# rsync -arv --exclude="/Lindsay" --exclude="/trash" --exclude="/Ω" --exclude="/V2X/Providers" $DATA_FOLDER $DATA_BACKUP